# Generated by Django 3.1.4 on 2024-04-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_review',
            new_name='num_reviews',
        ),
    ]
